services:

  oech-postgres:
    image: postgres:latest
    container_name: oech-postgres
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  oech-mongo:
#    image: mongo
#    container_name: oech-mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: chat_service
#    ports:
#      - '27017:27017'
#    volumes:
#      - dbdata6:/data/db
#  oech-RabbitMQ:
#    image: rabbitmq:3-management-alpine
#    container_name: oech-RabbitMQ
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password
#    ports:
#      - 5672:5672
#      - 15672:15672
#
#  oech-redis:
#    image: redis:latest
#    container_name: oech-redis
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - /path/to/local/d–∞ta:/root/redis
#      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - REDIS_PASSWORD=my-password
#      - REDIS_PORT=6379
#      - REDIS_DATABASES=16

volumes:
  postgres_data:
  dbdata6:

networks:
  oech-network:
    driver: bridge
