services:

  oech-postgres:
    image: postgres:latest
    container_name: oech-postgres
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  oech-mongo:
    image: mongo
    container_name: oech-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: chat_service
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  postgres_data:
  dbdata6:

networks:
  oech-network:
    driver: bridge
