services:

  oech-postgres:
    image: postgres:latest
    container_name: oech-postgres
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oech-network

  pgadmin:
    container_name: oech-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    user: '$UID:$GID'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgAdmin/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db
    networks:
      - oech-network

  oech-api:
    image: oech-api:1.0
    container_name: oech-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10123:8080"
    depends_on:
      - oech-postgres
    networks:
      - oech-network


volumes:
  postgres_data:
  dbdata6:
  pgadmin-data:

networks:
  oech-network:
    driver: bridge
